### ISSUE TITLE
Check every query for a counter (`_total`) is `irate`'d, and that we never use `rate`

### ISSUE THREAD

**Issue by mshahzeb** [grafana/dashboard-linter#55]
Always use irate instead of rate.

**Comment by MrFreezeex** [comment]
Hi not sure about the explanation, it seems to me that this thread explain more the disadvantages using irate than anything else? I also think that rate should be preferred over irate almost everywhere...

**Comment by mshahzeb** [comment]
@MrFreezeex Yes that is the consensus and we will be putting in a check for that in the dashboard linter.

I will remove the link to the confusing discussion :)

**Comment by MrFreezeex** [comment]
Do you mind explaining why? I mean I very much agree to the the thread you posted that explain why irate skip metrics and the graph will be "incorrect" (quoting directly: `No, irate doesn’t capture spikes - it just returns random sample of data points for the given time series.`)... Also not sure if this is very much a consensus since even mimir dashboards seems to prefer rate over irate if I am not mistaken.

**Comment by tomwilkie** [comment]
Yeah I think in hindsight best not to mandate the use of irate; still worth having a rule that checks counters (ie anything ending in _total) is rate'd/irate'd/increased etc, no?
