### ISSUE TITLE
Target rules in dashboard linter

### ISSUE THREAD

**Issue by mshahzeb** [grafana/dashboard-linter#59]
- Dont allow unused targets to be present in the dashboard
- Check for targets with empty expressions

**Comment by rgeyer** [comment]
> * Check for targets with empty expressions

`target-promql-rule` already checks this, since an empty expression can not be parsed as promql. We could add this test case to the test suite, just to cover it.

Related, I just found on the awx mixin, which uses a panel reference as it's target, that the linter does not support this case. Explicitly because, the `target-promql-rule` attempts to parse the `expr`, but there isn't one.

```
[target-promql-rule] 'AWX': Dashboard 'AWX', panel 'License Type' invalid PromQL query '': 1:1: parse error: no expression found in input
```

The linter should permit these type of targets, and should validate that the referenced panel/query exists.
```
"targets": [
            {
               "panelId": 3,
               "refId": "A"
            }
         ],
```
